<<<<<<< HEAD
# ===== SERVER =====
server.port=8080
spring.application.name=pegi-backend
# ===== DATABASE (sesuaikan dengan MySQL kamu) =====
spring.datasource.url=jdbc:mysql://localhost:3306/pegi_db?serverTimezone=Asia/Jakarta
=======
spring.application.name=PegiGo
#nama database nya pegi_db kalo mau test create tabel aja di phpmyadmin : pegi_db
spring.datasource.url=jdbc:mysql://localhost:3306/pegi_db
>>>>>>> c91da32dcea5ff206c22158102a9c616f2cc724e
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Konfigurasi JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== JWT (Haikal) =====
# Konfigurasi Email Pengirim (Gunakan Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adehaikal3@gmail.com
# Gunakan "App Password" dari Google, BUKAN password email asli
spring.mail.password=hzng xkuo jpgr fcau
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===== JWT =====
# Ganti secret ini dengan string random panjang (minimal 32 karakter)
jwt.secret=pegi-super-secret-key-2024-kelompok-1-uin-sgd
jwt.expiration=86400000

logging.level.com.pegi.backend.security=DEBUG
